# Generated by Django 5.2.5 on 2025-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={},
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='unidade',
            field=models.CharField(choices=[('caixa', 'Caixa'), ('carteira', 'Carteira')], default='carteira', max_length=10),
        ),
    ]
