# Generated by Django 5.2.8 on 2025-11-29 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_options_itemvenda_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
