# Generated by Django 5.2.5 on 2025-08-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_options_alter_venda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=20),
        ),
    ]
