# Generated by Django 5.2.8 on 2025-11-30 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
