# Generated by Django 5.2.5 on 2025-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola'), ('pos', 'POS'), ('transferencia', 'Transferência Bancária')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
