# Generated by Django 5.2.5 on 2025-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_remove_venda_status_alter_venda_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='preco_unitario',
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
