# Generated by Django 5.2.5 on 2025-08-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_remove_itemvenda_preco_unitario_alter_itemvenda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total_desconto',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda'),
        ),
    ]
