# Generated by Django 5.2.5 on 2025-08-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_remove_itemvenda_desconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='nfe_emitida',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='numero_nfe',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='observacoes',
        ),
    ]
