# Generated by Django 5.2.5 on 2025-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_remove_itemvenda_lote_remove_venda_nfe_emitida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
