# Generated by Django 5.2.5 on 2025-08-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='observacoes',
        ),
    ]
