# Generated by Django 5.2.5 on 2025-08-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('higiene', 'Higiene'), ('perfumaria', 'Perfumaria'), ('suplemento', 'Suplemento'), ('conveniencia', 'Convêniencia')], default='medicamento', max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.PositiveIntegerField(default=10)),
                ('forma_farmaceutica', models.CharField(blank=True, choices=[('comprimido', 'Comprimido'), ('capsula', 'Cápsula'), ('xarope', 'Xarope'), ('injecao', 'Injetável'), ('pomada', 'Pomada'), ('supositorio', 'Supositório'), ('spray', 'Spray'), ('outro', 'Outro')], max_length=50, null=True)),
                ('dosagem', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_prescricao', models.CharField(blank=True, choices=[('niv0', 'Niv 0'), ('niv1', 'Niv 1'), ('niv2', 'Niv 2'), ('niv3', 'Niv 3'), ('niv4', 'Niv 4')], default='niv0', max_length=50, null=True)),
                ('principio_ativo', models.CharField(blank=True, max_length=100, null=True)),
                ('controlado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('data_validade', models.DateField()),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.produto')),
            ],
        ),
    ]
