# Generated by Django 5.2.5 on 2025-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='carteiras_por_caixa',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_carteira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
