# Generated by Django 5.2.5 on 2025-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_produto_carteiras_por_caixa_produto_preco_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nr_caixas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
