# Generated by Django 5.2.5 on 2025-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_lote_nr_caixas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
