# Generated by Django 5.2.7 on 2025-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_lote_quantidade_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
