# Generated by Django 5.2.5 on 2025-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_lote_quantidade_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
