# Generated by Django 5.2.8 on 2025-11-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nr_carteiras',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
