# Generated by Django 5.2.8 on 2025-11-30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_lote_nr_carteiras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['data_validade'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='lote',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nr_caixas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='carteiras_por_caixa',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
