# Generated by Django 5.2.8 on 2025-11-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_categoria_options_alter_lote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='data_criacao',
        ),
    ]
